//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearning.Common.SMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/dtcsms/sms_elearning", ConfigurationName="SMSService.sms_elearningSoap")]
    public interface sms_elearningSoap {
        
        // CODEGEN: Generating message contract since element name message_template from namespace http://tempuri.org/dtcsms/sms_elearning is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dtcsms/sms_elearning/send_elearning_sms", ReplyAction="*")]
        eLearning.Common.SMSService.send_elearning_smsResponse send_elearning_sms(eLearning.Common.SMSService.send_elearning_smsRequest request);
        
        // CODEGEN: Generating message contract since element name dtc_driver_id from namespace http://tempuri.org/dtcsms/sms_elearning is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dtcsms/sms_elearning/send_elearning_sms_from_DTC_contacts", ReplyAction="*")]
        eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsResponse send_elearning_sms_from_DTC_contacts(eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_elearning_smsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="send_elearning_sms", Namespace="http://tempuri.org/dtcsms/sms_elearning", Order=0)]
        public eLearning.Common.SMSService.send_elearning_smsRequestBody Body;
        
        public send_elearning_smsRequest() {
        }
        
        public send_elearning_smsRequest(eLearning.Common.SMSService.send_elearning_smsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/dtcsms/sms_elearning")]
    public partial class send_elearning_smsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message_template;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string destination_mobile_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string driver_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string driver_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Param3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Param4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Param5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Param6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string mode;
        
        public send_elearning_smsRequestBody() {
        }
        
        public send_elearning_smsRequestBody(string message_template, string destination_mobile_no, string driver_id, string driver_name, string Param1, string Param2, string Param3, string Param4, string Param5, string Param6, string user_name, string pwd, string mode) {
            this.message_template = message_template;
            this.destination_mobile_no = destination_mobile_no;
            this.driver_id = driver_id;
            this.driver_name = driver_name;
            this.Param1 = Param1;
            this.Param2 = Param2;
            this.Param3 = Param3;
            this.Param4 = Param4;
            this.Param5 = Param5;
            this.Param6 = Param6;
            this.user_name = user_name;
            this.pwd = pwd;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_elearning_smsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="send_elearning_smsResponse", Namespace="http://tempuri.org/dtcsms/sms_elearning", Order=0)]
        public eLearning.Common.SMSService.send_elearning_smsResponseBody Body;
        
        public send_elearning_smsResponse() {
        }
        
        public send_elearning_smsResponse(eLearning.Common.SMSService.send_elearning_smsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/dtcsms/sms_elearning")]
    public partial class send_elearning_smsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string send_elearning_smsResult;
        
        public send_elearning_smsResponseBody() {
        }
        
        public send_elearning_smsResponseBody(string send_elearning_smsResult) {
            this.send_elearning_smsResult = send_elearning_smsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_elearning_sms_from_DTC_contactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="send_elearning_sms_from_DTC_contacts", Namespace="http://tempuri.org/dtcsms/sms_elearning", Order=0)]
        public eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsRequestBody Body;
        
        public send_elearning_sms_from_DTC_contactsRequest() {
        }
        
        public send_elearning_sms_from_DTC_contactsRequest(eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/dtcsms/sms_elearning")]
    public partial class send_elearning_sms_from_DTC_contactsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dtc_driver_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string file_number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date_time_of_test;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string test_name;
        
        public send_elearning_sms_from_DTC_contactsRequestBody() {
        }
        
        public send_elearning_sms_from_DTC_contactsRequestBody(string dtc_driver_id, string file_number, string date_time_of_test, string test_name) {
            this.dtc_driver_id = dtc_driver_id;
            this.file_number = file_number;
            this.date_time_of_test = date_time_of_test;
            this.test_name = test_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_elearning_sms_from_DTC_contactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="send_elearning_sms_from_DTC_contactsResponse", Namespace="http://tempuri.org/dtcsms/sms_elearning", Order=0)]
        public eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsResponseBody Body;
        
        public send_elearning_sms_from_DTC_contactsResponse() {
        }
        
        public send_elearning_sms_from_DTC_contactsResponse(eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/dtcsms/sms_elearning")]
    public partial class send_elearning_sms_from_DTC_contactsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string send_elearning_sms_from_DTC_contactsResult;
        
        public send_elearning_sms_from_DTC_contactsResponseBody() {
        }
        
        public send_elearning_sms_from_DTC_contactsResponseBody(string send_elearning_sms_from_DTC_contactsResult) {
            this.send_elearning_sms_from_DTC_contactsResult = send_elearning_sms_from_DTC_contactsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sms_elearningSoapChannel : eLearning.Common.SMSService.sms_elearningSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sms_elearningSoapClient : System.ServiceModel.ClientBase<eLearning.Common.SMSService.sms_elearningSoap>, eLearning.Common.SMSService.sms_elearningSoap {
        
        public sms_elearningSoapClient() {
        }
        
        public sms_elearningSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sms_elearningSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sms_elearningSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sms_elearningSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eLearning.Common.SMSService.send_elearning_smsResponse eLearning.Common.SMSService.sms_elearningSoap.send_elearning_sms(eLearning.Common.SMSService.send_elearning_smsRequest request) {
            return base.Channel.send_elearning_sms(request);
        }
        
        public string send_elearning_sms(string message_template, string destination_mobile_no, string driver_id, string driver_name, string Param1, string Param2, string Param3, string Param4, string Param5, string Param6, string user_name, string pwd, string mode) {
            eLearning.Common.SMSService.send_elearning_smsRequest inValue = new eLearning.Common.SMSService.send_elearning_smsRequest();
            inValue.Body = new eLearning.Common.SMSService.send_elearning_smsRequestBody();
            inValue.Body.message_template = message_template;
            inValue.Body.destination_mobile_no = destination_mobile_no;
            inValue.Body.driver_id = driver_id;
            inValue.Body.driver_name = driver_name;
            inValue.Body.Param1 = Param1;
            inValue.Body.Param2 = Param2;
            inValue.Body.Param3 = Param3;
            inValue.Body.Param4 = Param4;
            inValue.Body.Param5 = Param5;
            inValue.Body.Param6 = Param6;
            inValue.Body.user_name = user_name;
            inValue.Body.pwd = pwd;
            inValue.Body.mode = mode;
            eLearning.Common.SMSService.send_elearning_smsResponse retVal = ((eLearning.Common.SMSService.sms_elearningSoap)(this)).send_elearning_sms(inValue);
            return retVal.Body.send_elearning_smsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsResponse eLearning.Common.SMSService.sms_elearningSoap.send_elearning_sms_from_DTC_contacts(eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsRequest request) {
            return base.Channel.send_elearning_sms_from_DTC_contacts(request);
        }
        
        public string send_elearning_sms_from_DTC_contacts(string dtc_driver_id, string file_number, string date_time_of_test, string test_name) {
            eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsRequest inValue = new eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsRequest();
            inValue.Body = new eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsRequestBody();
            inValue.Body.dtc_driver_id = dtc_driver_id;
            inValue.Body.file_number = file_number;
            inValue.Body.date_time_of_test = date_time_of_test;
            inValue.Body.test_name = test_name;
            eLearning.Common.SMSService.send_elearning_sms_from_DTC_contactsResponse retVal = ((eLearning.Common.SMSService.sms_elearningSoap)(this)).send_elearning_sms_from_DTC_contacts(inValue);
            return retVal.Body.send_elearning_sms_from_DTC_contactsResult;
        }
    }
}
